To build the library, type:

./configure

followed by:

make

You might also consider to bulid the examples found
under the directory 'demos' by typing:

make examples

If you run into trouble or want to crosscompile for
gp2x, try:

./configure --help

to get a list of available platforms and supported
cross compilation kits.
