-- ToME - Tales of Maj'Eyal
-- Copyright (C) 2009, 2010, 2011 Nicolas Casalini
--
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see <http://www.gnu.org/licenses/>.
--
-- Nicolas Casalini "DarkGod"
-- darkgod@te4.org

newLore{
	id = "troll-poem",
	category = "misc",
	name = "trollish poem",
	lore = [[#{bold}#"Me Likes to Club"

#{italic}#Club club club,
Grab some grub!
When hunger hits,
Me likes to club!

Little halfling,
Furry feet,
Smash his brains,
Tasty meat!

Skinny elf,
Eyes so blue,
Crush his bones,
Make elf stew!

Hairy dwarf,
Smells like dirt,
Cook him long,
Or stomach hurt!

Stupid human,
Has no fear,
Looks surprised,
When me eats his ear!

Club club club,
Grab some grub!
When hunger hits,
Me likes to club!#{normal}#]],
}

newLore{
	id = "necromancer-poem",
	category = "misc",
	name = "necromancer poem",
	lore = [[#{bold}#"The Necromancer's Canticle"

#{italic}#Saved from coffin, casket, urn
Darkness falls, but life returns!
Flesh may fall and bone may burn
But soul remains, for which we yearn

Those we return to life's esteem
We see their hearts, their eyes do gleam
They rave! They kill! They gnash! They scream!
So full of joy! Their greatest dream!

Returning those that we amend
They hurry home, a distant friend
But do they cheer? Do they commend?
They yell! Does rotting flesh offend?

We bring life to lifeless bone
But do they smile? Do they condone?
They sit upon their golden thrones
They shun us, spurn us, make unknown

Fools! Sit high in golden tower
From your lofty perch you glower
Time will come when you will cower
We rule death, we wield the power
#{normal}#]],
}

newLore{
	id = "necromancer-primer-1",
	category = "misc",
	name = "how to be a necromancer, part 1",
	lore = [[#{bold}#THE GLORIOUS ART#{normal}#

Have you cast away the feeble pretensions of your society? Does your soul thirst for the taste of real power? Do you wish to have the strength to deny that most prevalent force, death itself? The glorious art of necromancy shall fulfil your wishes in ways you couldn't possibly imagine.

#{italic}#1. Your First Steps#{normal}#

Be aware, necromancy isn't all weaving mighty spells of undeath, wearing flowing black robes and crushing entire nations beneath the feet of your mighty undead horde; you'll have to put in some elbow grease as well. Your first few bodies will have to be stolen away personally as few people will aid a necromancer willingly, and those that do are rarely competent. The cemeteries of small towns and villages are good sites for your first acquisitions, but if time demands it don't be afraid to "make" some specimens of your own with the aid of a sharp knife or heavy bludgeon. Once you have your first minions out performing your bidding you needn't worry about resources any longer; opportunities to practice your art will, quite literally, pile up.

Also important is the upkeep of the bodies themselves. True, this is not strictly necessary as sufficient enchantment can bestow mobility upon even the most ruined and incomplete remains, but making sure that the joints and cruses of your prospective minions move freely and with ease much reduces the will required to grant them reanimation. It also makes for a sturdy and reliable base in case you desire to undertake larger, more audacious projects (see 46. Bone Giants & You).

Still not sure what to do? Then suffer and perish. Necromancy does not abide the inept.]]
}

newLore{
	id = "necromancer-primer-2",
	category = "misc",
	name = "how to be a necromancer, part 2",
	lore = [[#{italic}#2. Domination Of The Deceased#{normal}#

A contentious issue arises when it comes time to breathe life into your gathered specimens - do you raise them as lifeless drones, or do you bind the souls of the deceased within their vessels once more? There is much disagreement on this between the various movements of necromancers. The Beinagrind method of necromancy extols the torturous imprisonment of the soul as fundamental; the anguish generated by the captive spirit makes for a much more effective undead thrall, they claim. The recently founded Trené method however disagrees, claiming that allowing souls freedom not only results in more obedient slaves less prone to rising up and slaughtering their masters, but also causes your work to become marginally more acceptable to the unwashed masses. Sure, they'll still thrash you, drag you through town and burn you at the stake if they get the chance, but they'll feel ambivalent about it, by thunder!

Remember, when utilising a runic circle to bend your new minions to your will, make sure beforehand that every rune in the circle is enchanted properly and in no danger of fizzling out. If the unthinkable happens and one of your thralls is freed from your control, offer them goods or equipment in exchange for your life. Few undead will kill their creators after receiving such an act of generosity.]]
}

newLore{
	id = "necromancer-primer-3",
	category = "misc",
	name = "how to be a necromancer, part 3",
	lore = [[#{italic}#3. Unwanted Attention#{normal}#

Sadly, it is not only the peasantry and our "virtuous" archmage cousins that disapprove of our work. Though not entirely understood, necromancy is known to create "ripples" of a sort across the many dimensions, ripples that attract extra-planar attention. As a necromancer's power grows, so do said ripples, until eventually said necromancer finds all manner of demonic force and entity beating down their door, both mentally and physically.

Once again, opinions differ on this demonic interference. Necromancy is such a beautiful, divergent art, is it not? The Trené method sees the necromancer's corruption by outside forces as a negative thing, and practitioners of said method often take measures to divert supernatural attention from themselves, creating talismans to act as spiritual "conductors" or living close to the communities that despise them, the life essences of the masses masking the necromancer's dark emanations. On the other hand, the Beinagrind method welcomes the cursed whisperings that come from the demonic realms, believing it to be the completion of their psyches. Only once their spirits have been "corrupted" (a term Beinagrind practitioners scoff at) do people realize their true ambitions, they claim. Why these "true ambitions" always seem to be the utter and complete destruction of all life in this world and the summoning of unthinkable atrocities from the outer dimensions is unexplored.

You may have noticed that no instruction has been given on how to deal with the attention of common folk. That is because a true necromancer requires none. They are vermin, fit only to be crushed.]]
}

newLore{
	id = "necromancer-primer-4",
	category = "misc",
	name = "how to be a necromancer, part 4",
	lore = [[#{italic}#4. Necromancers Of Maj'Eyal#{normal}#

The greatest enemy of the necromancer is other necromancers. Well, apart from the Ziguranth, the Allied Kingdoms, the Shaloren, the Thaloren, the Iron Throne, common townsfolk, undead hunters, adventurers, rogue undead and Linaniil. But apart from them, the greatest enemy of the necromancer is other necromancers. Below is listed the location of many notable necromancers, areas possessing above-average undead activity, and other regions considered unfitting for our designs. Budding practitioners of our art are encouraged to perform their work away from these areas, lest they be recognized as threats or nuisances and are subsequently eradicated.

#{italic}#The Ruins Of Kor'Pul#{normal}#: While this necromancer of old may have perished, and his shade has long since lost any trace of sanity, his lair remains a nexus of dark energies, and his minions remain legion.

#{italic}#Blighted Ruins#{normal}#: An ambitious amateur has made his lair within these ruins, thought to be chasing dreams of raising an unstoppable army of the dead. His methods are known to be crude and prone to failure, and I fully expect to hear of him perishing at the hands of his own works within the year.

#{italic}#Dreadfell#{normal}#: Undead have been massing at this abandoned tower in unprecedented numbers. Obviously, a powerful figure has recently made it his home. Regardless, no clue has been given to the identity of this tower's supposed master.

#{italic}#Derth#{normal}#: While there is no formal necromancer presence in this sleepy countryside village, no practitioner of our art has been able to work within its vicinity. Rumours on why this is so are wild and varied, ranging from stories of almost all of its inhabitants being undead minions wearing cloaks of deception, to it being the secret base of the founder of the Trené method of necromancy. Whatever reason there is, beware.

#{italic}#Zigur#{normal}#: The enemy of our enemy is not our friend in this case. What passes for "normal" magic is enough to send the cult residing here into a frothing, psychotic frenzy - the presence of a necromancer would be enough to instigate a second Age of Pyre!

No further aid awaits you, for we do not tolerate the dependent. All that remains is for you to prove yourself worthy of practising this glorious art...]]
}

newLore{
	id = "halfling-feet",
	category = "misc",
	name = "of halfling feet",
	lore = [[Some men have said that the feet of halflings can nay be harmed, not by fire, blade nor magic. And they do say that this is a truly astounding thing. And some men consider the foot of a halfling to be an item of great luck and protection, and many have one hung above their door or mantle. Though these days 'tis frowned upon to go hunt for one, so 'tis considered a prized heirloom to be passed from father to son.

But women do look upon men and declare them fools. "For how," say they, "Can the foot of a halfling be a lucky thing, when with their large uncomely feet they are not able to wear shoes and footwear of elegant crafts and beauteous materials? And especially 'tis a great misfortune unto them, as with their short stature they could really do with a decent pair of heels..."

And lo, 'tis little mystery why halflings do look upon humans and say "The Big Folk really are very dumb."]]
}

newLore{
	id = "rogue-poem",
	category = "misc",
	name = "Rogues do it from behind",
	lore = [[An archer from the northern lands
Claimed of his great renown
With peerless skill and countless trials
His name known town to town

He spoke of facing vampire lords
Who promised years of pain
The archer gave a stern retort
An arrow through the brain

A fighter from the southern lands
Claimed armies fled his might
With dragons slain 'most every day
And demons crushed by night

He spoke of ancient sprawling ruins
Home to a ghastly shade
Its years of madness, hate and rage
Were ended on his blade

An archmage from the western lands
Claimed kingdoms feared his name
With countless legends, songs and myths
Attesting to his fame

He spoke of fire, storm and hail
To match the fiercest wyrm
To see one man hold so much power
Can make an empire squirm

A rogue who came from unknown lands
Not known for anything
A leap, a flash, a concealed blade
Three heroes felt its sting

The archer dropped, his bow unplucked
The fighter died as well
The archmage found its poison
Far too potent to dispel

The rogue is unknown to this day
Though rumours persist still
Rogues aren't known by name or deed
But by the names they kill]]
}
